"""Unit tests for manifests/tools/update_imagestream_annotations_from_pylock.py."""

from __future__ import annotations

from manifests.tools.update_imagestream_annotations_from_pylock import (
    accelerator_stack_version_from_lockfile,
)


def test_accelerator_stack_cuda_from_uv_header() -> None:
    text = """# This file was autogenerated by uv via the following command:
#    uv pip compile … --default-index=https://example/rhoai/3.4/cuda13.0-ubi9/simple/?format=json
lock-version = "1.0"
"""
    assert accelerator_stack_version_from_lockfile(text, "cuda") == "13.0"


def test_accelerator_stack_rocm_from_wheel_url() -> None:
    text = """# comment
wheels = [{ url = "https://pkgs/redhat/rhoai/3.4/rocm6.4-ubi9/pkg.whl" }]
"""
    assert accelerator_stack_version_from_lockfile(text, "rocm") == "6.4"


def test_accelerator_stack_from_requirements_index_url() -> None:
    text = """--index-url https://console.redhat.com/api/pypi/public-rhai/rhoai/3.4/cuda12.9-ubi9/simple/
foo==1.0
"""
    assert accelerator_stack_version_from_lockfile(text, "cuda") == "12.9"


def test_accelerator_stack_cpu_none() -> None:
    assert accelerator_stack_version_from_lockfile("cuda13.0-ubi9\n", "cpu") is None


def test_accelerator_stack_missing_returns_none() -> None:
    assert accelerator_stack_version_from_lockfile("name = foo\n", "cuda") is None
