FROM registry.access.redhat.com/ubi9/python-311:latest AS base

WORKDIR /opt/app-root/bin

# Other apps and tools installed as default user
USER 1001

# Install micropipenv to deploy packages from Pipfile.lock
RUN pip install --no-cache-dir -U "micropipenv[toml]"

ARG PYTORCH_SOURCE_CODE=jupyter/pytorch/ubi9-python-3.11

# Install Python packages and Jupyterlab extensions from Pipfile.lock
COPY ${PYTORCH_SOURCE_CODE}/Pipfile.lock ./

RUN echo "Installing softwares and packages" && \
    micropipenv install && \
    rm -f .//Pipfile.lock

WORKDIR /opt/app-root/src
