#!/usr/bin/env python3
"""Convert a pylock.toml (PEP 751) to a pip-compatible requirements.txt.

This helper is called by create-requirements-lockfile.sh (Step 2) to transform
a uv-generated pylock.toml lock file into a requirements.txt that pip, uv, and
cachi2/Hermeto can consume.

Why not just use pylock.toml directly?
  - pip and cachi2 don't support pylock.toml (PEP 751) yet.
  - requirements.txt with --hash lines is the common format understood by
    pip install --require-hashes, uv pip install --verify-hashes, and cachi2
    pip prefetch.

Usage:
    python3 pylock-to-requirements.py [--sdist-hashes MODE] \\
        <pylock.toml> <requirements.txt> [index-url]

Arguments:
    pylock.toml       Input lock file (PEP 751 format, generated by uv pip compile)
    requirements.txt  Output file path
    index-url         (optional) PyPI index URL to emit as --index-url header line.
                      If omitted or empty, the URL is taken from the uv compile comment
                      in the pylock (--default-index=...) so the requirements file matches
                      the index the lock was resolved against.

    --sdist-hashes    el9-fallback (default): omit sdist hashes when an EL9-compatible
                      wheel exists (RH-index / Hermeto wheel prefetch).
                      prefer: same sdist policy as el9-fallback (kept as the
                      public-index generator flag). Including sdists when an EL9
                      wheel exists makes Hermeto run cargo vendor on incomplete
                      Rust sdists such as ripgrep.

Output format:
    Each package entry becomes a line like:
        name==version ; marker \\
            --hash=sha256:abc123 \\
            --hash=sha256:def456

    Pure-Python packages (py3-none-any.whl) have a single hash.
    Native/binary packages have one hash per architecture wheel.
    Sdist hashes follow --sdist-hashes (see above). Both modes omit the sdist
    when an EL9-compatible wheel exists.

    Packages locked as a direct URL (uv ``archive``) become ``name @ URL`` so
    pip/Hermeto do not look them up on the index (e.g. tensorflow-rocm from AMD).

    If index-url is provided, it is emitted as the first line:
        --index-url https://...
"""

from __future__ import annotations

import argparse
import re
import sys
import tomllib
from pathlib import Path
from urllib.parse import parse_qsl, urlencode, urlparse, urlunparse

from packaging.utils import InvalidWheelFilename, parse_wheel_filename

# uv pip compile records its index in the first-line comment, e.g.
#   --default-index=https://pypi.org/simple
_DEFAULT_INDEX_RE = re.compile(r"--default-index=(https?://\S+)")

# UBI9/EL9 ships glibc 2.34. manylinux_2_35+ wheels cannot be installed there.
# Target EL9 off-host (this converter does not run on UBI9), so sys_tags() is wrong.
_MAX_EL9_GLIBC = (2, 34)

SDIST_HASHES_EL9_FALLBACK = "el9-fallback"
SDIST_HASHES_PREFER = "prefer"

# Konflux notebook images build these four Linux arches. ``prefer`` omits the sdist
# hash when EL9-compatible wheels cover every Konflux arch the package marker installs on.
KONFLUX_EL9_ARCHES = frozenset({"x86_64", "aarch64", "ppc64le", "s390x"})
_PLATFORM_MACHINE_EQ_RE = re.compile(r"platform_machine\s*==\s*['\"]([^'\"]+)['\"]")


def strip_format_json_param(index_url: str) -> str:
    parsed = urlparse(index_url)
    query_items = [
        (key, value)
        for key, value in parse_qsl(parsed.query, keep_blank_values=True)
        if not (key == "format" and value == "json")
    ]
    normalized_query = urlencode(query_items, doseq=True)
    return urlunparse(parsed._replace(query=normalized_query))


def _platform_is_el9_compatible(platform: str) -> bool:
    """Return True if a packaging Tag.platform can install on UBI9/EL9 (glibc 2.34)."""
    if platform == "any" or platform.startswith(("manylinux1_", "manylinux2010_", "manylinux2014_")):
        return True
    if platform.startswith("manylinux_"):
        # PEP 600: manylinux_{major}_{minor}_{arch}
        parts = platform.split("_")
        return (
            len(parts) >= 4
            and parts[1].isdigit()
            and parts[2].isdigit()
            and (int(parts[1]), int(parts[2])) <= _MAX_EL9_GLIBC
        )
    return False


def _konflux_arch_from_platform(platform: str) -> str | None:
    """Return the Konflux arch encoded in a wheel platform tag, if any."""
    if platform in KONFLUX_EL9_ARCHES:
        return platform
    for arch in KONFLUX_EL9_ARCHES:
        if platform.endswith(f"_{arch}"):
            return arch
    return None


def konflux_arches_required(marker: str) -> frozenset[str]:
    """Return Konflux arches a package installs on, inferred from its PEP 508 marker.

    ``uv export`` gates Jupyter-native deps with ``platform_machine == 'x86_64' or
    ... == 'aarch64'``. Ungated packages (no ``platform_machine``) install on all
    four Konflux arches, so ``prefer`` still keeps the sdist when an arch lacks
    an EL9 wheel.
    """
    found = frozenset(_PLATFORM_MACHINE_EQ_RE.findall(marker)) & KONFLUX_EL9_ARCHES
    return found or KONFLUX_EL9_ARCHES


def wheel_el9_arches(url_or_name: str) -> frozenset[str]:
    """Return Konflux EL9 arches this wheel can install on.

    Uses ``parse_wheel_filename`` Tag.platform values only — never the
    distribution name (e.g. a package named manylinux2010_helper).
    ``py3-none-any`` covers every Konflux arch. musllinux / too-new manylinux
    tags are ignored even when they share a filename with an EL9 tag.
    """
    try:
        *_, tags = parse_wheel_filename(url_or_name.rsplit("/", 1)[-1])
    except InvalidWheelFilename:
        return frozenset()

    arches: set[str] = set()
    for tag in tags:
        platform = tag.platform
        if not _platform_is_el9_compatible(platform):
            continue
        if platform == "any":
            return KONFLUX_EL9_ARCHES
        arch = _konflux_arch_from_platform(platform)
        if arch is not None:
            arches.add(arch)
    return frozenset(arches)


def wheel_is_el9_compatible(url_or_name: str) -> bool:
    """Return True if this wheel can install on UBI9/EL9 (glibc 2.34)."""
    try:
        *_, tags = parse_wheel_filename(url_or_name.rsplit("/", 1)[-1])
    except InvalidWheelFilename:
        return False
    return any(_platform_is_el9_compatible(tag.platform) for tag in tags)


def collect_index_hashes(pkg: dict, *, sdist_hashes: str = SDIST_HASHES_EL9_FALLBACK) -> list[str]:
    """Return wheel ``--hash=`` lines; sdist hashes depend on ``sdist_hashes``.

    ``el9-fallback`` (default) and ``prefer``: add sdist hashes only when no
    EL9 wheel exists. ``prefer`` is kept for the public-index generator; it
    must not re-introduce Rust sdists (ripgrep, uv) that break Hermeto
    ``cargo vendor``.
    """
    hashes: list[str] = []
    has_el9_wheel = False
    covered_arches: set[str] = set()
    for whl in pkg.get("wheels", []):
        for algo, digest in whl.get("hashes", {}).items():
            hashes.append(f"--hash={algo}:{digest}")
        url = whl.get("url", "")
        if wheel_is_el9_compatible(url):
            has_el9_wheel = True
        covered_arches.update(wheel_el9_arches(url))

    include_sdist = sdist_hashes in (SDIST_HASHES_EL9_FALLBACK, SDIST_HASHES_PREFER) and not has_el9_wheel
    if include_sdist:
        sdist = pkg.get("sdist")
        if isinstance(sdist, dict):
            for algo, digest in sdist.get("hashes", {}).items():
                hashes.append(f"--hash={algo}:{digest}")
    return hashes


def extract_default_index_from_pylock(pylock_path: Path) -> str:
    """Return --default-index URL from the uv autogeneration comment, or ""."""
    try:
        head = pylock_path.read_text(encoding="utf-8", errors="replace")[:8192]
    except OSError:
        return ""
    m = _DEFAULT_INDEX_RE.search(head)
    return strip_format_json_param(m.group(1).rstrip("'\"")) if m else ""


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("pylock_toml", type=Path, help="Input PEP 751 pylock.toml")
    parser.add_argument("requirements_txt", type=Path, help="Output requirements.txt path")
    parser.add_argument(
        "index_url",
        nargs="?",
        default="",
        help="Optional --index-url header. Empty uses the pylock --default-index comment.",
    )
    parser.add_argument(
        "--sdist-hashes",
        choices=(SDIST_HASHES_EL9_FALLBACK, SDIST_HASHES_PREFER),
        default=SDIST_HASHES_EL9_FALLBACK,
        help="When to emit sdist hashes (default: el9-fallback). prefer is an alias.",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    pylock_path: Path = args.pylock_toml
    output_path: Path = args.requirements_txt
    index_url = args.index_url.strip() or extract_default_index_from_pylock(pylock_path)

    # Parse the pylock.toml (PEP 751 format, requires Python 3.11+ for tomllib)
    with open(pylock_path, "rb") as f:
        data = tomllib.load(f)

    lines = []

    # Emit --index-url as the first line so pip/uv know where to find packages
    if index_url:
        lines.append(f"--index-url {index_url}")

    # Process each [[packages]] entry from the lock file
    for pkg in data.get("packages", []):
        name = pkg["name"]
        version = pkg["version"]
        marker = pkg.get("marker", "")  # e.g. "sys_platform == 'linux'"

        archive = pkg.get("archive")
        if isinstance(archive, dict) and (archive_url := (archive.get("url") or "").strip()):
            # Direct URL (not on PyPI): PEP 508 "name @ URL" so prefetchers fetch this file.
            hashes = [f"--hash={algo}:{digest}" for algo, digest in archive.get("hashes", {}).items()]
            entry = f"{name} @ {archive_url}"
            if marker:
                entry += f" ; {marker}"
            if hashes:
                entry += " \\\n" + " \\\n".join(f"    {h}" for h in hashes)
            lines.append(entry)
            continue

        hashes = collect_index_hashes(pkg, sdist_hashes=args.sdist_hashes)

        entry = f"{name}=={version}"
        if marker:
            entry += f" ; {marker}"
        if hashes:
            entry += " \\\n" + " \\\n".join(f"    {h}" for h in hashes)

        lines.append(entry)

    # Write the output file
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines) + "\n")

    pkg_count = len(lines) - (1 if index_url else 0)
    print(f"  Generated {output_path} ({pkg_count} packages)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
