FROM registry.access.redhat.com/ubi9/python-311:latest AS base

WORKDIR /opt/app-root/bin

# Other apps and tools installed as default user
USER 1001

# Install micropipenv to deploy packages from Pipfile.lock
RUN pip install --no-cache-dir -U uv

ARG MINIMAL_SOURCE_CODE=jupyter/minimal/ubi9-python-3.11

USER 1001

COPY ${MINIMAL_SOURCE_CODE}/requirements.txt ${MINIMAL_SOURCE_CODE}/start-notebook.sh ./

# Install Python dependencies from Pipfile.lock file
RUN echo "Installing softwares and packages" && \
    uv pip install -r requirements.txt && \
    rm -f ./requirements.txt

WORKDIR /opt/app-root/src

ENTRYPOINT ["start-notebook.sh"]